CREATE PROCEDURE Insert_Profile
@NewName NVARCHAR(500),
@Direction NVARCHAR(500)
AS
DECLARE @NAM VARCHAR (500)
DECLARE @CURSOR CURSOR
DECLARE @Flag INT = 0

SET @CURSOR  = CURSOR SCROLL
FOR
SELECT NAME FROM  Profiles

OPEN @CURSOR
FETCH NEXT FROM @CURSOR INTO @NAM
WHILE @@FETCH_STATUS = 0
BEGIN
        IF (@NewName=@NAM)
        BEGIN
		 SET @Flag = 1;
        END
FETCH NEXT FROM @CURSOR INTO @NAM
END
CLOSE @CURSOR
IF (@Flag=0)
 BEGIN
  INSERT INTO Profiles VALUES(@NewName, (SELECT ID FROM Directions WHERE Name = @Direction))
 END